### ISSUE TITLE
docker build Step 3/9 failed

### ISSUE THREAD

**Issue by yfhmmx** [sx1989827/DOClever#13]
Status: Downloaded newer image for node:6.10.3
 ---> 3f3928767182
Step 2/9 : MAINTAINER pollyduan pollyduan@163.com
 ---> Running in 328e5c6029c8
 ---> 7d5fcf195679
Removing intermediate container 328e5c6029c8
Step 3/9 : RUN apt-get update   && apt-get install -yqq supervisor mongodb   && apt-get clean && rm -rf /var/lib/apt/lists/*
 ---> Running in cdaace371d34
Err http://security.debian.org jessie/updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://deb.debian.org jessie InRelease
  
Err http://deb.debian.org jessie-updates InRelease
  
Err http://deb.debian.org jessie Release.gpg
  Could not resolve 'deb.debian.org'
Err http://deb.debian.org jessie-updates Release.gpg
  Could not resolve 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'deb.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'deb.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Unable to locate package supervisor
E: Unable to locate package mongodb
The command '/bin/sh -c apt-get update   && apt-get install -yqq supervisor mongodb   && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by sx1989827** [comment]
你好  docker的镜像是群里的朋友弄的 要不你加下群：611940610  和大家一起讨论下这个问题~
