### ISSUE TITLE
本地部署报错

### ISSUE THREAD

**Issue by wq409813230** [sx1989827/DOClever#17]
本地部署报let声明错误，使用严格模式启动后又报不支持可变参数错误，我使用的是master分支，node6.10.0，linux下不熟的

![qq 20170720141901](https://user-images.githubusercontent.com/9315085/28403347-e82035d8-6d56-11e7-981d-6103edcc3202.png)

**Comment by sx1989827** [comment]
你好 建议加下群：611940610  我们qq聊，这样问题更容易解决~

**Comment by wq409813230** [comment]
嗯，谢谢啦，是我自己大意了，之前装过一个版本较低的node

**Comment by qushaoye2009** [comment]
➜  DOClever git:(master) ✗ npm start

> DOClever@0.0.0 start /www/DOClever/DOClever
> node ./Server/bin/www

/www/DOClever/DOClever/Server/app.js:30
(async function () {
       ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/www/DOClever/DOClever/Server/bin/www:7:11)

npm ERR! Linux 3.10.0-862.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! DOClever@0.0.0 start: `node ./Server/bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the DOClever@0.0.0 start script 'node ./Server/bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the DOClever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./Server/bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs DOClever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls DOClever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /www/DOClever/DOClever/npm-debug.log
