### ISSUE TITLE
写文档说明时你们的参数校验规则，如长度，参数详细说明写在哪里

### ISSUE THREAD

**Issue by y-fly-dragon** [sx1989827/DOClever#18]
写文档说明时你们的参数校验规则，如长度，参数详细说明写在哪里

@sx1989827

**Comment by sx1989827** [comment]
你说的参数效验规则是指哪一块的？

**Comment by loverto** [comment]
比如说长度 后台的校验正则表达式

**Comment by loverto** [comment]
全部都写在备注里么

**Comment by sx1989827** [comment]
每个参数都会有一个备注的，写在备注里就可以了

**Comment by loverto** [comment]
![image](https://user-images.githubusercontent.com/3992018/28448051-8a31677e-6e07-11e7-80a3-a333f802b29c.png)

**Comment by loverto** [comment]
比如说这个

**Comment by sx1989827** [comment]
含义和最大长度写在参数说明里即可

**Comment by loverto** [comment]
那用什么分割呢？   
比如说，含义：令牌，最大长度：19，参数说明，1代表创建。2，代表新增，3，代表修改，4.代表啊啊啊，5，代表bbb，   
那么这样的说明这么写，你觉得怎么样

**Comment by loverto** [comment]
可不可以自定义备注列

**Comment by sx1989827** [comment]
这个可以你自己决定啊 用什么格式都是可以的 备注列目前还没有啊

**Comment by sx1989827** [comment]
你可以加群：611940610  有问题我们可以qq上门具体讨论
