### ISSUE TITLE
无法对接口中array类型列表数据进行导入

### ISSUE THREAD

**Issue by yileye** [sx1989827/DOClever#21]
当接口数据有array类型的数据时，在做返回值导入时候使用json方式导入，array中的内容无法显示出来，只能显示出array中的第一个数据

**Comment by anchorgoogle** [comment]
对，我也存在这个问题。

**Comment by sx1989827** [comment]
是这样的 数组导入只会解析第一项数据 因为是生成数据模型 不是导入所有数据

**Comment by sx1989827** [comment]
目前json导入可以把数组全部数据导入进来了
