### ISSUE TITLE
关于用户管理这块的建议

### ISSUE THREAD

**Issue by angunuan** [sx1989827/DOClever#23]
1.希望能有个管理后台，能统一管理用户的，比如注销删除用户等。现在除非是进数据库操作，否则连存在多少用户都不知道
2.用户的密码不要用明文存储

**Comment by sx1989827** [comment]
好的  这个需求会尽快实现

**Comment by Bosn** [comment]
Stars6k+Fork1.7k目前最火热的接口管理工具RAP #27

传送门：https://github.com/thx/RAP

9.25日创始人强势回归，大企业和大多数人的选择。有问题随时小窗我哦。~~~

**Comment by sx1989827** [comment]
用户管理后台已添加
