### ISSUE TITLE
请问为什么接口运行的例子里面，没有 path variable 的配置

### ISSUE THREAD

**Issue by magicliang** [sx1989827/DOClever#25]
目前接口运行界面，只有 query 和 header 的设值控件。
但有些 OAS 的 URI 的文档参数是 /teache/{id}/student/{sid} 这种形式的。
如果有可能，应该允许用户把自定义的变量值赋给 uri，并且保存这种变量值，就好像保存 query 一样。

我现在在调试一些带有 path variable 的 URI，把 path variable 错写到 query 里才发现原来没有这种 global variable replacement 的功能，如果用户可以在 URI 定义的时候，定义一个变量而多处使用（比如在多个 query 里面引用同一个 variable 的值），会方便很多，如果能够直接 eval 这些变量的值，还可以起到局部编程的作用。

ps：
我调试的端口路径是个 echo api，大致上是 http://localhost:8888//echo/{word}  这样的 api。
直接访问这样的 uri 是合法的，可以返回 ”{word}“。但在 DOClever 里面不给 word 设值就会出 400 错误。
前端的 advance 页面没有任何错误信息，后台的控制台也都没有任何细节。
感觉这个 proxy 的 uri 有特殊的 URI 校验正则，而且还把错误吞掉了，不利于调试。

**Comment by sx1989827** [comment]
doclever是有的啊，你在path里面输入类似/teache/{id}/student/{sid} 的路径，在下面tab会出现param一项，自动识别id和sid的

**Comment by magicliang** [comment]
我试了一下，手动输入的话确实有 param，但，如果是导入 Swagger 的 json 格式文件就没有。这应该是一个很容易 reproduce 的 bug。

**Comment by Bosn** [comment]
Stars6k+Fork1.7k目前最火热的接口管理工具RAP #27

传送门：https://github.com/thx/RAP

9.25日创始人强势回归，大企业和大多数人的选择。有问题随时小窗我哦。~~~
