### ISSUE TITLE
docker的运行命令说明

### ISSUE THREAD

**Issue by gonedays** [sx1989827/DOClever#29]
原来的docker运行命令是docker run -d --name doclever -p 10000:10000 lw96/doclever ,
建议做一下修改，可以允许把数据文件夹存放在宿主机，看了Dockerfile，猜想数据文件是放在容器的文件夹 /data/db里的，启动命令是否应该改成docker run -d -v  宿主机目录:/data/db / --name doclever -p 10000:10000 lw96/doclever

**Comment by sx1989827** [comment]
恩 docker的部分是群里的朋友帮忙弄的 要不你加下群：611940610  一起讨论下 群里的做这个镜像的朋友帮你解答下~

**Comment by gonedays** [comment]
实验了，命令改成这样，可以把mongodb的数据文件存到宿主机
docker run -d --name doclever -p 10001:10000  -v 宿主机存放mongodb数据文件的目录:/data/db lw96/doclever
