### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lrjxhchina** [sx1989827/DOClever#30]
导出html功能 有bug  点击无效。生成文档的那个功能

**Comment by sx1989827** [comment]
可否具体描述下呢~

**Comment by lrjxhchina** [comment]
在接口那 点运行  弹出 运行窗口
点击运行生成返回数据
运行button 右边有生成 按钮
点击生成按钮 弹出窗口关闭 也没有生成文档

**Comment by sx1989827** [comment]
导出html的话生成是无效的 方式用户修改
