### ISSUE TITLE
关于存储的数据文件

### ISSUE THREAD

**Issue by gonedays** [sx1989827/DOClever#31]
作者您好，存储doclever相关数据的文件，应该都是在mongodb里吧? 我看了DOCKERFILE里的内容，只是apt安装了mongodb，没设置相关的数据文件路径，那应该是使用默认路径，也就是/var/lib/mongodb，可是很奇怪容器中这个路径下并没有数据文件，请问是在哪里做了修改呢？也没找到相关的设置，谢谢

**Comment by sx1989827** [comment]
最新版的docker里面好像没有包含mongodb的 需要自己挂载mongodb的

**Comment by gonedays** [comment]
这个理解，我是想问，您提供的docker镜像lw96/doclever，这个里面好像并没有设置mongodb的数据文件路径，这样的话默认应该是在/var/lib/mongodb，可是我进镜像里看了，也并没有，您的镜像是在哪里设置到其他路径了呢？

**Comment by sx1989827** [comment]
恩 是这样的 这个docker镜像是群里的朋友帮忙弄的 要不你加群：611940610  问下做这个镜像的朋友如何~

**Comment by gonedays** [comment]
好的

**Comment by gonedays** [comment]
抱歉，重新看了mongodb官网文档，确认mongodb默认的存储路径为/data/db, 而不是/var/lib/mongodb,我关掉吧
