### ISSUE TITLE
下载地址链接错误

### ISSUE THREAD

**Issue by lwl5219** [sx1989827/DOClever#33]
## 

__运行__ 页面 __内网环境__ 的提示中, `net.js` 的链接是 `/resource/net.js` 应该是 `/html/web/resource/net.js`
node环境的下载地址类似.

**Comment by sx1989827** [comment]
非常感谢你的问题，我这边及时修复，也非常欢迎你加入讨论群：611940610  有任何问题都可以在里面进行讨论~

**Comment by sx1989827** [comment]
已修复
