### ISSUE TITLE
关于node_modules

### ISSUE THREAD

**Issue by liujb** [sx1989827/DOClever#35]
第一次见到开源项目中把node_modules放到源码中托管....这种方式感觉很别扭，难怪git clone半小时还没下来。

**Comment by sx1989827** [comment]
主要是方便很多人内网部署，还有很多不熟悉node的，可以直接上手使用，这里有镜像地址：https://gitee.com/sx1989827/SBDoc  国内的，下载比较快

**Comment by yuu2lee4** [comment]
确实不太好。。。可以在部署的命令行中完成嘛

**Comment by Jing-ge-ge** [comment]
人家能开源就很了不起的，不要带着埋怨的目光。万一有一天人家不开源了，小伙伴们连用都没得用呢。我们应该多多支持这个项目，多多赞赏，共同进步。
