### ISSUE TITLE
[测试]>[轮询] 增加警告邮件发送出发策略，如“仅测试不通过”

### ISSUE THREAD

**Issue by nangua** [sx1989827/DOClever#36]
如题，在 [DOClever](http://doclever.cn/projectinfo/projectinfo.html) 官网中测试轮询配置页面，暂时还没发现有警告邮件发送策略相关的配置。

有时希望仅仅测试不通过才收到【告警】邮件，否则，每天被十几封邮件轰炸，很容易会将真正的【告警】邮件淹没。

谢谢您。

**Comment by sx1989827** [comment]
已添加
