### ISSUE TITLE
可否考虑增加对protobuf、msgpack等二进制协议的文档支持呢？

### ISSUE THREAD

**Issue by jack1582** [sx1989827/DOClever#39]
可否考虑增加对protobuf、msgpack等二进制协议的文档支持呢？

目前app的场景，以后后台对后台的场景下，使用protobuf、msgpack等格式较多。但是现有的都要以json方式来展示和测试，比较不方便。期望能支持二进制下的协议接口管理的测试

**Comment by sx1989827** [comment]
这个需要具体交流，你可以加群：238719519  具体交流下~
