### ISSUE TITLE
关于适用中的几点建议与希望支持的功能

### ISSUE THREAD

**Issue by SoyMeng** [sx1989827/DOClever#4]
> **界面**

- 现在只有在点击角标出才能展开，希望点击事件应该点击整个栏目触发。

![image](https://cloud.githubusercontent.com/assets/6083582/23935929/f6fd3050-0989-11e7-8e38-a8cc3965b00f.png)
- 栏目文字超出处理

![image](https://cloud.githubusercontent.com/assets/6083582/23935966/46236e06-098a-11e7-83f1-66b5fddebbb3.png)

- 现在接口运行方式为_blank一个窗口,体验比较差。

> **功能**

- 增加全局参数、header、cookie配置
   比如现在的注入功能，我觉得如果有这方面的需求更多的是对接口进行统一处理，这样可以方便作一些统一处理，比如token等
- 编辑参数，填值时，希望是一个key-value形式
   如果是一些状态值，希望在界面中可以展示中文信息，传值为数字或字符
![image](https://cloud.githubusercontent.com/assets/6083582/23936144/3c4ec0fa-098b-11e7-9c38-edabe22bf0b9.png)
- 接口以及接口分组的排序功能

暂时就是上面这些，希望这个项目越来越好！

**Comment by sx1989827** [comment]
1.界面这一块的问题我会及时修复的~
2.增加全局参数这一块我会好好想想的怎么去做的。
3.编辑参数填值这里，因为参数本身就是keyvalue形式，为什么填值还要是keyvalue形式呢？
4.排序这一块一直在考虑，怎么用一种更好的方式去做，是名称排序，还是创建时间排序等等

**Comment by SoyMeng** [comment]
# 关于第3点
当前填值的方式：
![image](https://cloud.githubusercontent.com/assets/6083582/23978803/e3016f24-0a30-11e7-8bc0-6ba3f2eeb9e9.png)
然后在run接口时：
![image](https://cloud.githubusercontent.com/assets/6083582/23978837/12510f28-0a31-11e7-9e11-bd571aeda934.png)

下拉框中展示的所填写的值，而我希望的是配置一个key-value,下拉框中可以展示中文释义。我觉得这个需求应该都会有点。

# 关于第4点

名称排序对于中文来说意义并不大，希望能支持自定义排序，这样可以拖动操作栏目来排序。当然这种实现方式可能会有点复杂。

**Comment by sx1989827** [comment]
目前界面这一块做了不少改进，你可以看一下最新的1.1.6版本！其他的地方正在跟进中~

**Comment by sx1989827** [comment]
目前功能这一块除了排序，其他的都已经实现了
