### ISSUE TITLE
DOClever-master\Server\node_modules\asyncawait\node_modules\fibers\bin\win32-x64-59\fibers.node` is missing.

### ISSUE THREAD

**Issue by yushan-yaojin** [sx1989827/DOClever#50]
DOClever-master\Server\node_modules\asyncawait\node_modules\fibers\bin\win32-x64-59\fibers.node` is missing.

![image](https://user-images.githubusercontent.com/23131866/33753710-a3d1cfd6-dc23-11e7-8852-fd5e3b279622.png)
![image](https://user-images.githubusercontent.com/23131866/33753716-aef3475a-dc23-11e7-9e45-869bd7c353e5.png)

**Comment by sx1989827** [comment]
这个是node的版本问题，请选用node的最新lts版本

**Comment by dorothynono** [comment]
node-v8.9.3-x64 这个版本可以使用嘛？还是会有这个报错信息

**Comment by sx1989827** [comment]
@dorothynono 你重新下个最新版本，应该可以了
