### ISSUE TITLE
DOClever后台添加用户总是报错

### ISSUE THREAD

**Issue by summer1897** [sx1989827/DOClever#53]
为什么我在DOClever后台添加用户的时候，在单击保存按钮后，总是提示,参数state必须为Number?
![doclever_error](https://user-images.githubusercontent.com/12208806/33936841-f06fae82-e03b-11e7-94e7-86b5a221aecf.png)
还有就是，怎么去除前台用户注册功能，只通过后台管理员添加用户来完成用户的添加，只能是手动改前端代码吗？

**Comment by sx1989827** [comment]
你好 ，这个问题我来看下，禁止注册的功能下一版本会加上的~

**Comment by sx1989827** [comment]
新版本已修复，注册禁用也已加上
