### ISSUE TITLE
https跨域问题

### ISSUE THREAD

**Issue by CUGxia** [sx1989827/DOClever#60]
网站部署https后网页还是会请求http,造成跨域,无法请求,请问如何解决?

**Comment by sx1989827** [comment]
目前doclever内部还是http写的 https的话不支持 这个后面会考虑的  感谢关注 建议加群：611940610  有问题可以及时讨论~

**Comment by lovelydeng** [comment]
我用nginx做反向代理，发现请求接口的时候 还是http的。这个应该比较好解决吧，在控制器生成请求链接的时候判断一下浏览器请求的 schema 是http还是https  就ok了。 这https不需要这个项目去支持，起码也得支持我们外部反向代理的配置吧。现在是配置了https，请求不了http的接口，被block掉了
