### ISSUE TITLE
restful参数中文异常bug

### ISSUE THREAD

**Issue by goubo** [sx1989827/DOClever#62]
如果在restful参数中传递中文，点击运行时会抱参数异常。
我看了一下js源码，有一步逐个添加所有请求数据到RequestHeader的操作，报错了
数据类型异常

**Comment by sx1989827** [comment]
restful中的path不建议用中文来写，这样会使restful的语义变得很不明确，也不是标准所向，建议加群：611940610 有问题可以及时讨论~
