### ISSUE TITLE
用例里面接口参数貌似插不进去，每次都要手动输入

### ISSUE THREAD

**Issue by fastluo** [sx1989827/DOClever#71]
用例里面接口参数貌似不能自动插进去，每次都要代码模式手动输入，况且那编辑器不是太好用,中文输入有问题。
![image](https://user-images.githubusercontent.com/31495325/35369127-8a65e80c-01c1-11e8-9811-41fdf53687eb.png)

**Comment by sx1989827** [comment]
可以试试桌面端 现在界面都已经换了
