### ISSUE TITLE
测试用例中，post 请求无法发送数组，会自动转化成对象

### ISSUE THREAD

**Issue by cheneywan** [sx1989827/DOClever#82]
![23b81972-08f0-4553-a1f2-bb0983097813](https://user-images.githubusercontent.com/2441562/38225200-547daa46-3726-11e8-82df-3eb3fb24d02b.png)
![8a53493c22ac9f47c35de0ca1a63a144](https://user-images.githubusercontent.com/2441562/38225224-7e99d052-3726-11e8-897e-f39c3621d593.jpg)

如图，很多场景下我们请求体中直接是一个数组，而非对象

这样的情况下，直接解析成了对象，很不科学

**Comment by BODhaha** [comment]
你好，我也遇到了这个问题，请问这个库还有在维护吗？

**Comment by sx1989827** [comment]
你好，这个问题最新版本已经解决 ，请升级到最新的桌面端

**Comment by cheneywan** [comment]
刚刚试了下，Web 版并没有修复
是不是以后 Web 版不维护了？
