### ISSUE TITLE
/lib64/libstdc++.so.6

### ISSUE THREAD

**Issue by sczhaoqi** [sx1989827/DOClever#83]
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /app/DOClever/Server/node_modules/fibers/bin/linux-x64-57/fibers.node)
Linux上部署为什么会有这个错误

**Comment by sczhaoqi** [comment]
:cry:

**Comment by kinvensan** [comment]
centos 7.2 上面一直报这个错误，不知道怎么调整？
