### ISSUE TITLE
无法导入swagger.json，提示服务器错误

### ISSUE THREAD

**Issue by shenbinglife** [sx1989827/DOClever#85]
我的swagger.json在swagger  editor中是正常的，没有提示任何错误。
如果需要该json文件测试，可以QQ我：1160243163

使用DOClever版本是 http://doclever.cn
Swagger版本：2.0
![image](https://user-images.githubusercontent.com/16119667/39106823-d70192d2-46f0-11e8-8d6e-2cce2c4e43f9.png)

**Comment by sx1989827** [comment]
请提供你的swagger json文件，可以加下qq群：611940610

**Comment by shenbinglife** [comment]
在群里交流了，发现私服搭建的可以正常导入。
