### ISSUE TITLE
接口测试能不能添加超时或者检验目标ip端口是否存在功能？

### ISSUE THREAD

**Issue by imic07** [sx1989827/DOClever#90]
1. 如题。当使用一个未启动服务的ip地址来访问时，一直在运行中。要等很久。。浪费时间和生命啊。
![image](https://user-images.githubusercontent.com/16321067/39691157-2c21d3e8-520f-11e8-80d9-89009f786328.png)

2. 能否像postman一样增加    取消请求 功能，否则一个接口在运行中，如果时间很长，只能刷新才能再次运行。

**Comment by sx1989827** [comment]
你可以用下桌面端 是可以取消请求发送的
